-- MySQL Script generated by MySQL Workbench
-- Wed Mar  2 19:58:33 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbcliente
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbcliente
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbcliente` DEFAULT CHARACTER SET utf8 ;
USE `dbcliente` ;

-- -----------------------------------------------------
-- Table `dbcliente`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcliente`.`cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(75) NOT NULL,
  `apellidos` VARCHAR(75) NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbcliente`.`tipoDocumento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcliente`.`tipoDocumento` (
  `idTipoDocumento` INT NOT NULL AUTO_INCREMENT,
  `tipoDocumento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoDocumento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbcliente`.`documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcliente`.`documento` (
  `idDocumento` INT NULL AUTO_INCREMENT,
  `numeroDocumento` VARCHAR(18) NOT NULL,
  `idCliente` INT NOT NULL,
  `idTipoDocumento` INT NOT NULL,
  PRIMARY KEY (`idDocumento`),
  INDEX `fk_documento_cliente_idx` (`idCliente` ASC),
  INDEX `fk_documento_tipoDocumento1_idx` (`idTipoDocumento` ASC),
  CONSTRAINT `fk_documento_cliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `dbcliente`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_documento_tipoDocumento1`
    FOREIGN KEY (`idTipoDocumento`)
    REFERENCES `dbcliente`.`tipoDocumento` (`idTipoDocumento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbcliente`.`departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcliente`.`departamento` (
  `idDepartamento` INT NOT NULL AUTO_INCREMENT,
  `departamento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDepartamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbcliente`.`municipio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcliente`.`municipio` (
  `idMunicipio` INT NOT NULL AUTO_INCREMENT,
  `municipio` VARCHAR(45) NOT NULL,
  `idDepartamento` INT NOT NULL,
  PRIMARY KEY (`idMunicipio`),
  INDEX `fk_municipio_departamento1_idx` (`idDepartamento` ASC),
  CONSTRAINT `fk_municipio_departamento1`
    FOREIGN KEY (`idDepartamento`)
    REFERENCES `dbcliente`.`departamento` (`idDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbcliente`.`direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcliente`.`direccion` (
  `idDireccion` INT NOT NULL AUTO_INCREMENT,
  `direccion` VARCHAR(100) NOT NULL,
  `idMunicipio` INT NOT NULL,
  `idCliente` INT NOT NULL,
  PRIMARY KEY (`idDireccion`),
  INDEX `fk_direccion_municipio1_idx` (`idMunicipio` ASC),
  INDEX `fk_direccion_cliente1_idx` (`idCliente` ASC),
  CONSTRAINT `fk_direccion_municipio1`
    FOREIGN KEY (`idMunicipio`)
    REFERENCES `dbcliente`.`municipio` (`idMunicipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_direccion_cliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `dbcliente`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbcliente`.`auditoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbcliente`.`auditoria` (
  `idAuditoria` INT NOT NULL AUTO_INCREMENT,
  `accion` VARCHAR(500) NOT NULL,
  `fecha` DATETIME NOT NULL,
  PRIMARY KEY (`idAuditoria`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
